apiVersion: v1
kind: Service
metadata:
  name: heroes-admin-service
spec:
  selector:
    app: heroes-admin-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes-admin-app
spec:
  selector:
    matchLabels:
      app: heroes-admin-app
  replicas: 1
  template:
    metadata:
      labels:
        app: heroes-admin-app
    spec:
      containers:
        - name: heroes-admin-app
          image: leonardobonacci/heroes-admin
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
